### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by wieczorek-kamil** [im-razvan/CS2_Grenade_Preview#2]
Triggerbot not working.

I updated the offsets, the trigger still doesn't work, the offsets were taken from the offset py and client dll py files

when holding the shift key because that is the default key, nothing happens.

**Comment by im-razvan** [comment]
Hi!

I don't offer support for the triggerbot code, but I might take a look into it. Please double check that the offsets you added are good.
PS. you wrote this in the [CS2_Grenade_Preview](https://github.com/im-razvan/CS2_Grenade_Preview) repository.
